[settings]
input_dir = /home/phillip/Seafile/CLIMWATER/Data/Hydrometeorology/Meteo
output_dir = /home/phillip/Seafile/CLIMWATER/Data/Hydrometeorology/CMIP6/
buffer_radius = 2000
show = True
sd_factor = 2
processes = 30
download = True
load_backup = False
start_region_index = 0
start_station_index = 0
cnp_format = True
cnp_climate_id = 999


; Optional for single-file CSV input
; single_station_lat = 41.97
; single_station_lon = 70.45
