[settings]
input_dir = /home/phillip/Seafile/Pflanzenbau_Boness/met/obs/Zehdenick/temp_prec.csv
output_dir = /home/phillip/Seafile/Pflanzenbau_Boness/met/cmip6/
buffer_radius = 2000
show = True
sd_factor = 2
processes = 30
download = True
load_backup = False
start_region_index = 0
start_station_index = 0
cnp_format = True
cnp_climate_id = 999


; Optional for single-file CSV input
single_station_lat = 52.9664
single_station_lon = 13.3268

